In [1]:
import os
import re
from scipy.io import loadmat
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import cv2

newfile = open("C:/IR Data/181127_155516/irdata_012.asc", 'r')
original = newfile.read()
fd= original[206:]
z = fd.split()
#print(type(z))

g = [ (float(x.replace(',','.'))) for x in z ]

y = np.asarray(g)
#print(y)
#print(y.shape)

d = y.reshape(512, 640)
x = d[0].flatten()
np.amin(x)
np.amax(x)

norm_image = cv2.normalize(d, None, alpha =np.amin(d), beta=np.amax(d), norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)
minval = np.amin(d)
maxval = np.amax(d)
#print(np.amin(d))
#print(np.amax(d))
norm_image = (d - minval)/(maxval-minval)
#print(norm_image)

cv2.imshow("normed", norm_image)
print(norm_image)
cv2.waitKey(0)


[[0.04252938 0.04196978 0.04252938 ... 0.01063234 0.01454952 0.01678791]
 [0.04029099 0.04252938 0.04196978 ... 0.         0.00447678 0.01175154]
 [0.03973139 0.03637381 0.03693341 ... 0.00335758 0.01007275 0.00727476]
 ...
 [0.04141018 0.04252938 0.03637381 ... 0.03021824 0.02518187 0.02797985]
 [0.04196978 0.0391718  0.03077784 ... 0.02462227 0.02350308 0.02853945]
 [0.05092334 0.04644656 0.04364857 ... 0.02909905 0.03189703 0.02853945]]


27

In [2]:
rows,cols = norm_image.shape

M = cv2.getRotationMatrix2D( (cols/2, rows/2 ),180,1)

dst = cv2.warpAffine(norm_image,M,(cols,rows))
cv2.imshow("img", dst)
print(dst)
cv2.waitKey(0)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.02853945 0.03189703 ... 0.03525462 0.04364857 0.04644656]
 [0.         0.02853945 0.02350308 ... 0.03189703 0.03077784 0.0391718 ]
 ...
 [0.         0.01287073 0.00727476 ... 0.04141018 0.0391718  0.04308898]
 [0.         0.00727476 0.01007275 ... 0.04420817 0.03693341 0.03637381]
 [0.         0.01175154 0.00447678 ... 0.03749301 0.04196978 0.04252938]]


27

In [ ]:
#cv2.imwrite('smalldot1.png',dst)
#cv2.imshow('', img.astype(np.uint8))

In [ ]:
# cv2.imshow("dots",dst)
# cv2.waitKey(0)

In [ ]:
cv2.imwrite('smalldot2.bmp',dst)
cv2.imshow("dots2",dst)
cv2.waitKey(0)


In [2]:
 
import cv2
 
# read image
img = cv2.imread('smalldot2.bmp', cv2.IMREAD_UNCHANGED)
 
# get dimensions of image
dimensions = img.shape
 
# height, width, number of channels in image
#height = img.shape[0]
#width = img.shape[1]
#channels = img.shape[2]
 
print('Image Dimension    : ',dimensions)
#print('Image Height       : ',height)
#print('Image Width        : ',width)
#print('Number of Channels : ',channels)

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
cv2.imshow("dots2",dst)
cv2.waitKey(0)