In [1]:
import os

#newfile = open("C:/IR Data/181127_135927_aicon_markers/irdata_450.asc", 'r')
newfile = open("C:/IR Data/181127_155220_small_circles_with_rect/irdata_018.asc", 'r')
original = newfile.read()
#print(original)

In [2]:
print(type(original))
#values of all the temp data
fd= original[206:]
#print(fd)
#print(type(fd))

<class 'str'>


In [3]:
z = fd.split()
#print(type(z))

In [4]:
import re
g = [  (float(x.replace(',','.'))) for x in z ]
#print(type(g[0]))
#print(g)


In [5]:
from scipy.io import loadmat
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import cv2

y = np.asarray(g)
#print(y)
#print(y.shape)

d = y.reshape(512,640)
#print(d.shape)
#print(type(d))

In [6]:
print(d[0].size)
print(d[0][0])
print(d[0][511])
x = d[0].flatten()
#print(x)
np.amin(x)
np.amax(x)

640
24.38
24.99


33.79

In [7]:
norm_image = cv2.normalize(d, None, alpha =np.amin(d), beta=np.amax(d), norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)
minval = np.amin(d)
maxval = np.amax(d)
print(np.amin(d))
print(np.amax(d))
norm_image = (d - minval)/(maxval-minval)
print(norm_image)

23.26
49.12
[[0.04331013 0.04601701 0.04331013 ... 0.05529776 0.05529776 0.05723125]
 [0.04756381 0.04331013 0.04601701 ... 0.05065739 0.05413766 0.05413766]
 [0.04485692 0.04176334 0.04060325 ... 0.04640371 0.05181748 0.05723125]
 ...
 [0.03325599 0.03016241 0.03054911 ... 0.02358855 0.02745553 0.02668213]
 [0.0317092  0.03054911 0.02861562 ... 0.02706883 0.02165507 0.02706883]
 [0.03828306 0.03480278 0.03402939 ... 0.0324826  0.02745553 0.02706883]]


In [8]:
                                      
cv2.imshow("normed", norm_image)
print(norm_image)
cv2.waitKey(0)

[[0.04331013 0.04601701 0.04331013 ... 0.05529776 0.05529776 0.05723125]
 [0.04756381 0.04331013 0.04601701 ... 0.05065739 0.05413766 0.05413766]
 [0.04485692 0.04176334 0.04060325 ... 0.04640371 0.05181748 0.05723125]
 ...
 [0.03325599 0.03016241 0.03054911 ... 0.02358855 0.02745553 0.02668213]
 [0.0317092  0.03054911 0.02861562 ... 0.02706883 0.02165507 0.02706883]
 [0.03828306 0.03480278 0.03402939 ... 0.0324826  0.02745553 0.02706883]]


13

In [9]:
rows,cols = norm_image.shape

M = cv2.getRotationMatrix2D( (cols/2, rows/2.5 ),270,1)

dst = cv2.warpAffine(norm_image,M,(cols,rows))

# cv2.namedWindow("output", cv2.WINDOW_NORMAL)        # Create window with freedom of dimensions                
#imS = cv2.resize(dst, (1536, 1280))                    # Resize image
cv2.imshow("img", dst)
cv2.waitKey(0)

13

In [10]:


cv2.imwrite('new7.bmp',dst*255)



True

In [11]:
cv2.imshow("bmp", dst)
cv2.waitKey(0)


13

In [12]:
print(norm_image.shape)

(512, 640)


In [ ]:
# imcp = norm_image.copy()
# imcp.shape
# imcp = cv2.resize(imcp,None, fx=2, fy=3)
# imcp.shape
# print(imcp.shape)